### ISSUE TITLE
無綫新聞

### ISSUE THREAD

**Issue by kenyiu** [code4hk/NewsdiffHK-Backend#3]
http://news.tvb.com/

**Comment by balling** [comment]
encoding problem?

```
2015-04-13 12:28:24.340:DEBUG:Retrieved http://news.tvb.com/finance/5524ebf86db28cb755000001/
2015-04-13 12:28:24.366:ERROR:Exception when parsing http://news.tvb.com/finance/5524ebf86db28cb755000001/
2015-04-13 12:28:24.367:ERROR:Traceback (most recent call last):
  File "/var/lib/openshift/5522485f5973ca68950001fe/app-root/runtime/repo/crawler/crawler.py", line 40, in load_article
    parsed_article = parser(url)
  File "/var/lib/openshift/5522485f5973ca68950001fe/app-root/runtime/repo/parsers/baseparser.py", line 55, in __init__
    self._parse(self.html)
  File "/var/lib/openshift/5522485f5973ca68950001fe/app-root/runtime/repo/parsers/tvb.py", line 31, in _parse
    print ('The title is: %s' % self.title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-19: ordinal not in range(128)
```

**Comment by kenyiu** [comment]
Should have fixed. Kindly check.
